select I001IX as 'IMPORTACION','ADUANA','FECHA','TIPO DE CAMBIO','IVA','CLAVE', 'FLETES', 'SEGUROS','EMBALAJES','OTROS','DTA','VALOR COMERCIAL','VALOR ADUANA','CONSOLIDADO','PREVALIDACION','FACTURA','FECHA FACTURA','FACTOR MONEDA','NUM_PART','TIPO BIEN','FRACCION IMPORTACION','DES_MERC','TASA','TIPO TASA','UNIDAD','PRECIO','CANTIDAD','ORIGEN','VENDEDOR','FORMA DE PAGO', 'INCOTERM','PAGA IMPUESTOS PARA TLCAN','PAGA IMPUESTOS PARA TLCUEM','EB','MONTO EB',	'COVE','MULTAS','RECARGOS','CNT','PESO NETO','PESO BRUTO' 
from at001
WHERE date(D001FECEP) in ("2011-02-14","2011-02-15","2011-02-16")
limit 10;

#Campos del reporte Reporte
#IMPORTACION	ADUANA	FECHA	TIPO DE CAMBIO	IVA	CLAVE	FLETES	SEGUROS	EMBALAJES	OTROS	DTA	VALOR COMERCIAL	VALOR ADUANA	CONSOLIDADO	PREVALIDACION	FACTURA	FECHA FACTURA	FACTOR MONEDA	NUM_PART	TIPO BIEN	FRACCION IMPORTACION	DES_MERC	TASA	TIPO TASA	UNIDAD	PRECIO	CANTIDAD	ORIGEN	VENDEDOR	FORMA DE PAGO	INCOTERM	PAGA IMPUESTOS PARA TLCAN	PAGA IMPUESTOS PARA TLCUEM	EB	MONTO EB	COVE	MULTAS	RECARGOS	CNT	PESO NETO	PESO BRUTO
select *
from at001
WHERE date(D001FECEP) in ("2011-02-14","2011-02-15","2011-02-16")
limit 10;