SELECT 
	C001TIPOPE AS 'IMPORTACION', 
    C001ADUSEC AS 'ADUANA', 
    D001FECARR AS'FECHA', 
    F001TIPCAM AS 'TIPO DE CAMBIO', 
    'IVA', 
    C001CVEDOC AS 'CLAVE',
    F001FLETES AS 'FLETES',
	F001VALSEG AS 'SEGUROS',
    F001EMBALA AS 'EMBALAJES',
    F001OTRINC AS 'OTROS', 
    F001TASDT1 AS 'DTA',
    'VALOR COMERCIAL', 
    N001VALADU AS'VALOR ADUANA',
    'CONSOLIDADO',
	F001TASPRE AS 'PREVALIDACION', 
    F001TOTFAC AS 'FACTURA', 
    'FECHA FACTURA', 
    F001FACMEX AS 'FACTOR MONEDA',
    'NUM_PART','TIPO BIEN', 
    'FRACCION IMPORTACION',
	'DES_MERC',
    'TASA',
    'TIPO TASA',
    'UNIDAD',
    'PRECIO',
    'CANTIDAD', 
    C001ORIGEN AS'ORIGEN',
    'VENDEDOR', 
    C001CONFOR AS'FORMA DE PAGO', 
    'INCOTERM', 
    F001TASREU AS'PAGA IMPUESTOS PARA TLCAN',
	'PAGA IMPUESTOS PARA TLCUEM',
    'EB',
    'MONTO EB',	
    'COVE', 
    F001TASMUL AS 'MULTAS', 
    F001TASREC AS 'RECARGOS',
    'CNT',
    'PESO NETO', 
    F001PESO AS 'PESO BRUTO' 
FROM at001
WHERE date(D001FECEP) BETWEEN '2016-01-01' AND '2016-01-31';

#Campos del reporte Reporte
#IMPORTACION	ADUANA	FECHA	TIPO DE CAMBIO	IVA	CLAVE	FLETES	SEGUROS	EMBALAJES	OTROS	DTA	VALOR COMERCIAL	VALOR ADUANA	CONSOLIDADO	PREVALIDACION	FACTURA	FECHA FACTURA	FACTOR MONEDA	NUM_PART	TIPO BIEN	FRACCION IMPORTACION	DES_MERC	TASA	TIPO TASA	UNIDAD	PRECIO	CANTIDAD	ORIGEN	VENDEDOR	FORMA DE PAGO	INCOTERM	PAGA IMPUESTOS PARA TLCAN	PAGA IMPUESTOS PARA TLCUEM	EB	MONTO EB	COVE	MULTAS	RECARGOS	CNT	PESO NETO	PESO BRUTO
select *
from at001;